version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST:localhost
      - POSTGRES_NAME:postgres
      - POSTGRES_PASSWORD:pass123
      - POSTGRES_PORT:5432
